#!/bin/bash

WIRE_READ=/bin/1wire_read
STORAGE_PATH=/var/wire2eth
STORAGE=temperature

if ! [ -d $STORAGE_PATH ]; then
        mkdir $STORAGE_PATH;
fi

$WIRE_READ > $STORAGE_PATH/$STORAGE.tmp && mv $STORAGE_PATH/$STORAGE.tmp $STORAGE_PATH/$STORAGE
